# Generated by Django 5.2.8 on 2025-11-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('1', 'abshode_naghd_farda'), ('2', 'abshode_naghd_pasfarda'), ('3', 'abshode_with_gateway'), ('4', 'seke_nim_1386'), ('5', 'seke_nim_sal_payeen_ta_80'), ('6', 'seke_rob_1386'), ('7', 'seke_rob_1403'), ('8', 'seke_rob_sal_payeen_ta_80'), ('9', 'seke_tamam_1386'), ('10', 'seke_tamam_1403'), ('11', 'seke_tamam_sal_payeen')], max_length=2)),
                ('base_price_sell', models.BigIntegerField(default=0)),
                ('base_price_buy', models.BigIntegerField(default=0)),
                ('time', models.TimeField(auto_now=True)),
                ('is_exist', models.BooleanField(default=True)),
            ],
        ),
    ]
